### ISSUE TITLE
步数传感器获取到的步数和手机自带app不一致

### ISSUE THREAD

**Issue by xysgx** [nesror/Home-Assistant-Companion-for-Android#13]
![image](https://github.com/user-attachments/assets/903d2190-72ae-4d7e-896e-93759b08e5e5)

![5356042af11c4f2654bc3d8747e9ed5](https://github.com/user-attachments/assets/177aa21b-d466-4730-a206-e73cc1f6c262)
使用红米K50 pro以及小米14ultra测试，同样的问题。
打开步数传感器之后获取到的步数和小米自带的运动app上的步数不一致。

**Comment by nesror** [comment]
步数是自开机起的步数，Android原生获取就是这样，和官方app保持一致。需要在ha自动化里处理。可以看下官方的文档
