### ISSUE TITLE
在外边使用时显示github的报错信息

### ISSUE THREAD

**Issue by sctale** [nesror/Home-Assistant-Companion-for-Android#4]
大佬，这个能修正一下吗？之前的版本和原版的HA APP都不会有这个情况。
![微信图片_20230115130445](https://user-images.githubusercontent.com/18475722/212524013-78c7fde2-c019-4221-8589-e694ec4de162.jpg)

**Comment by nesror** [comment]
这个是检查app更新用的，不影响功能。出现这个是访问手机网络访问GitHub不稳定造成的

**Comment by nesror** [comment]
最新版改成蒲公英的服务了
