### ISSUE TITLE
20230427的版本更新之后直接闪退，清空数据后无法登录使用

### ISSUE THREAD

**Issue by z0ow** [nesror/Home-Assistant-Companion-for-Android#6]
系统：鸿蒙3.0

**Comment by hncdbai** [comment]
我也这样，也是鸿蒙3.0

**Comment by z0ow** [comment]
> 我也这样，也是鸿蒙3.0

我试过清空数据，然后重装，等待很长一段时间后能开，但是一开后台定位就闪退，目前退回到上一个版本了。

**Comment by conscloud** [comment]
我这也是一样的情况，闪退。鸿蒙3.0

**Comment by nesror** [comment]
华为的好像都有问题。。晚点云调试下

**Comment by nesror** [comment]
https://github.com/nesror/Home-Assistant-Companion-for-Android/releases/tag/v2023-04-28
