### ISSUE TITLE
地理位置显示为未知

### ISSUE THREAD

**Issue by Hosiang1026** [nesror/Home-Assistant-Companion-for-Android#8]
设备：Google Piexl 5 手机 
系统版本：Android 13
HA版本： v2023-07-03v2
问题描述：APP已开启位置权限和地理编码，但是地理位置还是显示未知
求助：有没有办法像iOS官方版本一样，在APP可以手动获取位置，并进行位置记录显示
手机端：
![微信图片_20230703182646](https://github.com/nesror/Home-Assistant-Companion-for-Android/assets/28383042/754529fa-aba7-49f4-b6a5-4ac21872a993)

PC端：
![screenshot-20230703-183855](https://github.com/nesror/Home-Assistant-Companion-for-Android/assets/28383042/0341b749-1c9f-41e0-a141-a3895129ed63)

**Comment by nesror** [comment]
部分手机无法获取手机免费提供的逆地理编码(api返回为空)

1.可以尝试填写高德key，有免费api次数
2.可以使用SmartHouse（内置付费接口）
https://github.com/nesror/SmartHouse
